### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by Niconoko** [bakerj76/LCThirdPerson#1]
![image](https://github.com/bakerj76/LCThirdPerson/assets/24541618/60a2e327-d107-4fb8-8395-fde5a99e99ba)
Don't get me wrong, me was wondering if any plugins in the list me got may prevent 3rd person to work here.
PS. In the picture, me removed the 3rd person plugin out just to let ye see what in the list.

**Comment by bakerj76** [comment]
Thanks for the notice, on it now!

Right now, the only way to install it is by dropping both `crosshair.png` and `LCThirdPerson.dll` in a folder called `LCThirdPerson` in your plugins folder.

But I'll embed crosshair.png now, so it'll work with just the .dll.

**Comment by bakerj76** [comment]
Alright, changes made. Just drop the .dll in plugins and it should work!
