### ISSUE TITLE
Can I upload a fork of this project?

### ISSUE THREAD

**Issue by killfrenzy96** [bakerj76/LCThirdPerson#18]
Hi baker, I have been working on a fork of your project, and I'd like to upload and maintain it.

I may have uploaded a fork earlier, but I now realize that no license had been attached to your project that would permit this.

If you can, please let me know if this is okay to do so.

**Comment by bakerj76** [comment]
Yeah, totally! I’m glad you’re keeping it going.

**Comment by killfrenzy96** [comment]
Thanks for letting me work on it!
