### ISSUE TITLE
Third person on lethal company issue

### ISSUE THREAD

**Issue by Matherios** [bakerj76/LCThirdPerson#2]
Hello when you are on a ladder and using 3rd person you can't drop off the ladder.

**Comment by bakerj76** [comment]
Thanks for the heads up!

I’ll fix it ASAP.

**Comment by bakerj76** [comment]
Fixed in the latest update! Thanks again!

**Comment by Matherios** [comment]
Hello ty for the update on the ladder!
One issue with the update is that if you are looking in an angle it changes a bit the direction of your movements when you let go of the ladder at 3rd person

**Comment by Matherios** [comment]
Maybe a good fix is when climbing a ladder it forces you in 1st person?
