### ISSUE TITLE
Emotes don't show hands when switching back to first person

### ISSUE THREAD

**Issue by jacobmix** [bakerj76/LCThirdPerson#3]
Emotes don't show hands when switching back to first person.
They play, and i can see my character move, and such. But only hands show up in third person.

**Comment by bakerj76** [comment]
Thanks for the heads up!
Will fix!

**Comment by jacobmix** [comment]
Btw maybe disable the hotkey when in chat or terminal.

**Comment by bakerj76** [comment]
Fixed both of these in the latest update! Thanks again!
